-- Migration 0004 — capsule delete clears content metadata.
--
-- sha256, preview_poster_key, and preview_motion_key are nullable in
-- 0001. **object_key is NOT nullable in 0001** — that was a factual
-- error in the original version of this comment that led to the
-- production DELETE 500 incident (see 0008 for the schema fix).
--
-- This migration remains a schema-level sentinel confirming that the
-- owner-delete / account-delete flows are permitted to NULL content
-- columns when tombstoning a capsule_share row.
--
-- Retained fields (share_code, created_at, owner_user_id, size_bytes,
-- frame_count, atom_count) stay for audit + aggregate metrics.
--
-- Kept as a numbered file so the migration ledger stays ordered with
-- the plan's phase structure; wrangler `d1 migrations apply` will
-- record it as applied with no schema diff.
SELECT 1;
